const BREEDS = [
    {breedDetailId: 1, adoptionBreed: "Affenpinscher"},
    {breedDetailId: 2, adoptionBreed: "Afghan Hound"},
    {breedDetailId: 4, adoptionBreed: "Airedale Terrier"},
    {breedDetailId: 6, adoptionBreed: "Akita"},
    {breedDetailId: 9, adoptionBreed: "Alaskan Malamute"},
    {breedDetailId: 10, adoptionBreed: "American Bulldog"},
    {breedDetailId: 12, adoptionBreed: "American Eskimo Dog"},
    {breedDetailId: 14, adoptionBreed: "American Foxhound"},
    {breedDetailId: 16, adoptionBreed: "American Staffordshire Terrier"},
    {breedDetailId: 17, adoptionBreed: "American Water Spaniel"},
    {breedDetailId: 18, adoptionBreed: "Anatolian Shepherd"},
    {breedDetailId: 21, adoptionBreed: "Australian Cattle Dog / Blue Heeler"},
    {breedDetailId: 22, adoptionBreed: "Australian Kelpie"},
    {breedDetailId: 23, adoptionBreed: "Australian Shepherd"},
    {breedDetailId: 24, adoptionBreed: "Australian Terrier"},
    {breedDetailId: 28, adoptionBreed: "Basenji"},
    {breedDetailId: 30, adoptionBreed: "Basset Hound"},
    {breedDetailId: 31, adoptionBreed: "Beagle"},
    {breedDetailId: 32, adoptionBreed: "Bearded Collie"},
    {breedDetailId: 33, adoptionBreed: "Beauceron"},
    {breedDetailId: 34, adoptionBreed: "Bedlington Terrier"},
    {breedDetailId: 36, adoptionBreed: "Belgian Shepherd / Malinois"},
    {breedDetailId: 38, adoptionBreed: "Belgian Shepherd / Tervuren"},
    {breedDetailId: 41, adoptionBreed: "Bernese Mountain Dog"},
    {breedDetailId: 42, adoptionBreed: "Bichon Frise"},
    {breedDetailId: 43, adoptionBreed: "Black and Tan Coonhound"},
    {breedDetailId: 149, adoptionBreed: "Black Labrador Retriever"},
    {breedDetailId: 45, adoptionBreed: "Bloodhound"},
    {breedDetailId: 47, adoptionBreed: "Bluetick Coonhound"},
    {breedDetailId: 48, adoptionBreed: "Boerboel"},
    {breedDetailId: 50, adoptionBreed: "Border Collie"},
    {breedDetailId: 51, adoptionBreed: "Border Terrier"},
    {breedDetailId: 53, adoptionBreed: "Boston Terrier"},
    {breedDetailId: 54, adoptionBreed: "Bouvier des Flandres"},
    {breedDetailId: 55, adoptionBreed: "Boxer"},
    {breedDetailId: 56, adoptionBreed: "Boykin Spaniel"},
    {breedDetailId: 58, adoptionBreed: "Briard"},
    {breedDetailId: 59, adoptionBreed: "Brittany Spaniel"},
    {breedDetailId: 128, adoptionBreed: "Brussels Griffon"},
    {breedDetailId: 61, adoptionBreed: "Bull Terrier"},
    {breedDetailId: 64, adoptionBreed: "Bullmastiff"},
    {breedDetailId: 65, adoptionBreed: "Cairn Terrier"},
    {breedDetailId: 67, adoptionBreed: "Cane Corso"},
    {breedDetailId: 68, adoptionBreed: "Cardigan Welsh Corgi"},
    {breedDetailId: 69, adoptionBreed: "Catahoula Leopard Dog"},
    {breedDetailId: 70, adoptionBreed: "Caucasian Ovtcharka"},
    {breedDetailId: 71, adoptionBreed: "Cavalier King Charles Spaniel"},
    {breedDetailId: 76, adoptionBreed: "Chesapeake Bay Retriever"},
    {breedDetailId: 78, adoptionBreed: "Chinese Crested Dog"},
    {breedDetailId: 80, adoptionBreed: "Chinook"},
    {breedDetailId: 149, adoptionBreed: "Chocolate Labrador Retriever"},
    {breedDetailId: 81, adoptionBreed: "Chow Chow"},
    {breedDetailId: 84, adoptionBreed: "Clumber Spaniel"},
    {breedDetailId: 86, adoptionBreed: "Cocker Spaniel"},
    {breedDetailId: 68, adoptionBreed: "Corgi"},
    {breedDetailId: 89, adoptionBreed: "Coton de Tulear"},
    {breedDetailId: 92, adoptionBreed: "Dalmatian"},
    {breedDetailId: 94, adoptionBreed: "Doberman Pinscher"},
    {breedDetailId: 95, adoptionBreed: "Dogo Argentino"},
    {breedDetailId: 98, adoptionBreed: "Dutch Shepherd"},
    {breedDetailId: 179, adoptionBreed: "English Bulldog"},
    {breedDetailId: 86, adoptionBreed: "English Cocker Spaniel"},
    {breedDetailId: 101, adoptionBreed: "English Setter"},
    {breedDetailId: 102, adoptionBreed: "English Shepherd"},
    {breedDetailId: 103, adoptionBreed: "English Springer Spaniel"},
    {breedDetailId: 104, adoptionBreed: "English Toy Spaniel"},
    {breedDetailId: 110, adoptionBreed: "Finnish Lapphund"},
    {breedDetailId: 111, adoptionBreed: "Finnish Spitz"},
    {breedDetailId: 113, adoptionBreed: "French Bulldog"},
    {breedDetailId: 114, adoptionBreed: "German Pinscher"},
    {breedDetailId: 115, adoptionBreed: "German Shepherd Dog"},
    {breedDetailId: 116, adoptionBreed: "German Shorthaired Pointer"},
    {breedDetailId: 119, adoptionBreed: "Giant Schnauzer"},
    {breedDetailId: 120, adoptionBreed: "Glen of Imaal Terrier"},
    {breedDetailId: 121, adoptionBreed: "Golden Retriever"},
    {breedDetailId: 123, adoptionBreed: "Gordon Setter"},
    {breedDetailId: 124, adoptionBreed: "Great Dane"},
    {breedDetailId: 125, adoptionBreed: "Great Pyrenees"},
    {breedDetailId: 127, adoptionBreed: "Greyhound"},
    {breedDetailId: 129, adoptionBreed: "Harrier"},
    {breedDetailId: 130, adoptionBreed: "Havanese"},
    {breedDetailId: 134, adoptionBreed: "Irish Setter"},
    {breedDetailId: 135, adoptionBreed: "Irish Terrier"},
    {breedDetailId: 137, adoptionBreed: "Irish Wolfhound"},
    {breedDetailId: 138, adoptionBreed: "Italian Greyhound"},
    {breedDetailId: 140, adoptionBreed: "Japanese Chin"},
    {breedDetailId: 142, adoptionBreed: "Keeshond"},
    {breedDetailId: 144, adoptionBreed: "Komondor"},
    {breedDetailId: 147, adoptionBreed: "Kuvasz"},
    {breedDetailId: 149, adoptionBreed: "Labrador Retriever"},
    {breedDetailId: 153, adoptionBreed: "Lancashire Heeler"},
    {breedDetailId: 155, adoptionBreed: "Leonberger"},
    {breedDetailId: 156, adoptionBreed: "Lhasa Apso"},
    {breedDetailId: 161, adoptionBreed: "Maltese"},
    {breedDetailId: 167, adoptionBreed: "Miniature Pinscher"},
    {breedDetailId: 168, adoptionBreed: "Miniature Schnauzer"},
    {breedDetailId: 172, adoptionBreed: "Norfolk Terrier"},
    {breedDetailId: 176, adoptionBreed: "Norwich Terrier"},
    {breedDetailId: 177, adoptionBreed: "Nova Scotia Duck Tolling Retriever"},
    {breedDetailId: 178, adoptionBreed: "Old English Sheepdog"},
    {breedDetailId: 181, adoptionBreed: "Papillon"},
    {breedDetailId: 183, adoptionBreed: "Pekingese"},
    {breedDetailId: 184, adoptionBreed: "Pembroke Welsh Corgi"},
    {breedDetailId: 188, adoptionBreed: "Pharaoh Hound"},
    {breedDetailId: 189, adoptionBreed: "Plott Hound"},
    {breedDetailId: 193, adoptionBreed: "Pomeranian"},
    {breedDetailId: 201, adoptionBreed: "Pug"},
    {breedDetailId: 204, adoptionBreed: "Puli"},
    {breedDetailId: 205, adoptionBreed: "Pumi"},
    {breedDetailId: 207, adoptionBreed: "Rat Terrier"},
    {breedDetailId: 208, adoptionBreed: "Redbone Coonhound"},
    {breedDetailId: 209, adoptionBreed: "Rhodesian Ridgeback"},
    {breedDetailId: 210, adoptionBreed: "Rottweiler"},
    {breedDetailId: 212, adoptionBreed: "Saint Bernard"},
    {breedDetailId: 213, adoptionBreed: "Saluki"},
    {breedDetailId: 214, adoptionBreed: "Samoyed"},
    {breedDetailId: 216, adoptionBreed: "Schipperke"},
    {breedDetailId: 218, adoptionBreed: "Scottish Deerhound"},
    {breedDetailId: 219, adoptionBreed: "Scottish Terrier"},
    {breedDetailId: 221, adoptionBreed: "Shetland Sheepdog / Sheltie"},
    {breedDetailId: 222, adoptionBreed: "Shiba Inu"},
    {breedDetailId: 223, adoptionBreed: "Shih Tzu"},
    {breedDetailId: 226, adoptionBreed: "Siberian Husky"},
    {breedDetailId: 228, adoptionBreed: "Silky Terrier"},
    {breedDetailId: 232, adoptionBreed: "Smooth Fox Terrier"},
    {breedDetailId: 235, adoptionBreed: "Spanish Water Dog"},
    {breedDetailId: 236, adoptionBreed: "Spinone Italiano"},
    {breedDetailId: 238, adoptionBreed: "Staffordshire Bull Terrier"},
    {breedDetailId: 239, adoptionBreed: "Standard Schnauzer"},
    {breedDetailId: 242, adoptionBreed: "Swedish Vallhund"},
    {breedDetailId: 243, adoptionBreed: "Thai Ridgeback"},
    {breedDetailId: 244, adoptionBreed: "Tibetan Mastiff"},
    {breedDetailId: 245, adoptionBreed: "Tibetan Spaniel"},
    {breedDetailId: 246, adoptionBreed: "Tibetan Terrier"},
    {breedDetailId: 248, adoptionBreed: "Toy Fox Terrier"},
    {breedDetailId: 250, adoptionBreed: "Treeing Walker Coonhound"},
    {breedDetailId: 251, adoptionBreed: "Vizsla"},
    {breedDetailId: 253, adoptionBreed: "Weimaraner"},
    {breedDetailId: 254, adoptionBreed: "Welsh Springer Spaniel"},
    {breedDetailId: 256, adoptionBreed: "West Highland White Terrier / Westie"},
    {breedDetailId: 233, adoptionBreed: "Wheaten Terrier"},
    {breedDetailId: 257, adoptionBreed: "Whippet"},
    {breedDetailId: 115, adoptionBreed: "White German Shepherd"},
    {breedDetailId: 259, adoptionBreed: "Wire Fox Terrier"},
    {breedDetailId: 260, adoptionBreed: "Wirehaired Pointing Griffon"},
    {breedDetailId: 262, adoptionBreed: "Xoloitzcuintli / Mexican Hairless"},
    {breedDetailId: 149, adoptionBreed: "Yellow Labrador Retriever"},
    {breedDetailId: 264, adoptionBreed: "Yorkshire Terrier"}
];